name: Unit tests

on:
  push:
    branches:
      - master
    paths:
      - '**.go'
      - 'go.**'
      - .github/workflows/build.yaml
  pull_request:
    paths:
      - '**.go'
      - 'go.**'
      - .github/workflows/build.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache-dependency-path: go.sum

      - name: Install dependencies
        run: |
          go get .

      - name: Download SewerRat
        uses: wei/wget@v1
        with:
          args: -O SewerRat https://github.com/ArtifactDB/SewerRat/releases/download/latest/SewerRat-linux-amd64

      - name: Run tests
        run: |
            sudo chmod +x ./SewerRat
            ./SewerRat &
            go test -v

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        os: [ linux, darwin ]
        arch: [ amd64, arm64 ]

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Shift tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/latest',
              sha: context.sha
            });

      - name: Build latest
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.os }}
          goarch: ${{ matrix.arch }}
          release_tag: latest
          asset_name: SewerRat-${{ matrix.os }}-${{ matrix.arch }}
          overwrite: true
          compress_assets: false
