name: Publish version

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v1

  publish:
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        os: [ linux, darwin ]
        arch: [ amd64, arm64 ]

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Publish binaries
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.os }}
          goarch: ${{ matrix.arch }}
          release_tag: ${{ github.ref_name }}
          asset_name: SewerRat-${{ matrix.os }}-${{ matrix.arch }}
          overwrite: true
          compress_assets: false
